sudo: required
language: java
jdk: openjdk8
services:
- docker
env:
  global:
  - secure: "WniGpjO5Ek3p6Ug01Koot1f3gvUomCTDMArIHEnmNHyS0fiT7lXDPxFLTMpYFm2S0zk7LogOIM6lIwJkL52SBqYAR7oTr52PGSx1yOqPaDpy4WuKNjKm4d3j8G18cg6PPTRuf8MTuqwZnN9DPOGfr/QE0dxxn3OLxOToR+bbOqmKFbzh3/fHgKi5QW/uniIE4JuEYq1pCSCNYt71Cs/DLXDPdgfJ3GIlg3OC8BEIFi3CGYIXiuUCk1EbhxLhjFwaA5azcp6+QfPhbfIsqbVSlQux18znJvDc7/83oTLDLvZhpU2rNKELloMnXlJfq/HNTk6K4S+vMgWi1z/QSDKTENwAAsvBj3AmsxD31/zW0iUM3Zukr5OTPy3irdEExDsq/lc4uraNeDGOEDqAItUKO5wnwdCumxUtRd4RlT4gFfAVxNgyyqi0ND86/habRxjqnfUwh57edgNMqu+34MTkEWIP6ZAtHdgSu87ggI85pA5JDgfsvLZMnkbRg2dtWo7IFIeB86xlL3tIUZlojQxk0y5zjfVCOhCeXBRZSxjulH/B0zuO2KvtbQQTc9X5IAIzBM/e0Ucc26Fbg7QXrb38gRbLTnREsXucbhAfjjAd/VerWdRpGxsYalqG3drf7QKkyBlPdaXhI9Gnv102qqrTbxOaAT0k8uJXBhXcQalSe58="
  - secure: "jAQQb1iQArMe+Bo7tdDg8QRZVOyec4xwcby9lQkTGrhVpT7BGEUx7iMbNVb1XR2E3R/og5eawI6DKKW9M90iFWMSYCdfRxNcYxmb2qW2kaj2vP5ri83dSJtYpKHeJf2yO0PttvZRapC57Z1sIWrs04om4nZ+otjPnNhXhz0i3eJWeqLhvDQV4Upu5pwMhkKU+tihwh3c2doM0ww9XGe4ZQLH12KDRSJTMby13VSXlYhsJR3h5cnK4yR6A7xebs6Zph4KDz5ITF62zArvgHv9enf+e2RSCljPnljxJin/qy4zLrkEdgqzQfVJSPbQjkUHJqjhPNth0o7m1A0pzng5sjm3UTFfdrK0h+DXu9zaVuHkVfS2dWZ7PwWC1YMOG3mXlpiuMJsTrpMfmxrbga7KiPBsRae81byC0GCbwiOAc5GVoNUHNBR92Fw9LERQatltIJkuo+XHB4EZdbgq8hWZX7nrpPFTs479j1t8zrQP0E6neGc//q74cvKusVzw9Ov+sjrA/65gsVrtN7FKxViBlMWWyP5AYAULjguptmvD8HdBxUuJ33cuze+PKCyXWmYUvY+PgQq8D18SBS0U2s/ZqVnxhrWKlbQ1aLF0sHu/j5FOovOiFzuJDGSMOQYl1eSLK3tTUNXLAoHvsWcwMfqKaDtgUqJEJyvCrfE6tDLPGEA="
  - secure: "lbXmIOcqMHHjVOFY2WHomv7GiIGpRHV/0BnjpQHJJUAF+tsPU9DX7xwaPQpH3Gftbua5bK0nNI9WtrnxAC+eaxrJAgveKMNza99dRr7BiHQNQGE4MtZNd/Lf9CVhuM9RX1X21K9fWncASC+Bi7Yb/OGxx/64yzWWawhyAlK3oyGZXkqeX/O1THDtJkmh6GxsqOcRAH3SLfIA0yc9HoUSueUe0i23q4SI9R2MURot5S/BwgtnyYLBll09UakrTcwW9ytkeCyfJbW3At+/1cy2KhO3021+/uLBV85Bl2wgdMd75FP5VauxElPrYqwQVqkSdD6IXmSoyeOyl1T7QHc4wbcJCP/5rYwPesIrR4ugCzX1yvPV8qoW+j62IEiCMrDfjPHIYHRZAqQKx27lhOnIhsHVY4punAZvVTvsdD/vd5tHCvqjqGnQrttuoD6075ZTAsaGmQHJe+P4OWU3C14ws1IWU6X8W3qZ97h4gWSInqZnxal4OJqc2OkalPwVJt/LKLBVyLOZ62uQrmIjW8sB4J8xRb22skxm8T98QJJ+64UVI/nPauMpMqO/AFSKc7eHDbrqmJaPbfIdm+HnG0j58LvzkMMmlb2SVHkEB4hVb8UF9F6K2+/7kC9X6JZTC+58K5tDa1GXKWujnUShWEUI29tSmf8F1x6pW82ARKyR++o="
  - secure: "FG3IjnY9zOVSLr+9XjA2nbEODcjqTjw/OTWg1EjHoZiW4q12gGmz3lOvaYNYeYPzndS3hBWqfcVV/hSdyxF3I8UrLWqYFmREaUWj+n5TE6jsPkBtTTgpplOdJtryihvDz6MU3VqUtdJh1d2/jRMHSDriKzW8MR5eNf2tErEb6qtPK8a4NQOmbN5dDOmTFqTD5cMEbOjLx+CUpQMmjaVVJU2ZgZaZUSws9Z/yh583XoQODmxtiLpK6t2XUBzte4mTkaX55lD7jHKiGrd+HV5/KDg9b+U6Rvxo3Enw/azZx1JzRdaIvpwVqFWvQikUZXZx+foIWVos4bnao/s0rs3QLq1DqPTXw+fR22yiIhEr8VWrou+oiUVuhVjvZn4MoujSkWnyQ65QocjSnnOeExLZruDM2tKePZIyIU+67MOYzDiqiNUQj9VV4jqeCvxzvmaL4duUbQNkXjNbu5P7EEcoXhki3yjCjzwTABRyFRw0lufyZ40XEaIIj8XFgxiRrZclUM/HCVLN3ZhbTWTONQS9vvpPajhZD8xaItsFqBF+sSbZE8iK6JXzto0t/MHXqSw+z1tp04bLmbuuTgtYCNXmRZb2X1x3bmvGVrOA2s8QSRDzwNUsiubaqvrZZY1MzuW8H7JruJEJD0Zx3Zd1sf9U2DaIcqL7yXvyfzTkpB3gN3c="
  - COMMIT=${TRAVIS_COMMIT::7}

git:
  depth: 500

addons:
  sonarcloud:
    organization: "sam-kaz-github"
    token:
      secure: $SONAR_TOKEN

script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export IMAGE_NAME=sydkaz/freelancer-kit
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: freelancer-kit-syed
